In [5]:
import numpy as np

# 1) Examen

## 2) Crear un vector de ceros de tamaño 10

vector_ceros = np.zeros(10)
print(vector_ceros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [8]:
## 3) Crear un vector de ceros de tamaño 10 y el de la posicion 5 sea igual a 1
vector_ceros2 = np.zeros(10)
vector_ceros2[5]=1
print(vector_ceros2)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


In [14]:
## 4) Cambiar el orden de un vector de 50 elementos, 
## el de la posicion 1 es el de la 50 etc.
arr=np.arange(50)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


In [15]:
arr[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [42]:
## 5) Crear una matriz de 3 x 3 con valores del cero al 8

np.array([0,1,2,3,4,5,6,7,8]).reshape(3,3)


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [24]:
np_array = np.array((1, 5, 9, 3, 7, 2, 0))
np.where(np_array == 0)

(array([6], dtype=int64),)

In [54]:
## 6) Encontrar los indices que no sean cero en un arreglo
arreglo = ([1,2,0,0,4,0])

In [220]:


index=[]
for i in range(len(arreglo)):
    if arreglo[i]is not 0:
        index.append(i)

print(index)

[0, 1, 4]


In [221]:
index=np.where(np.array(arreglo) != 0)
print(index)

(array([0, 1, 4], dtype=int64),)


In [60]:
## 7) Crear una matriz de identidad 3 x 3 
matriz_i = np.eye(3)
print(matriz_i)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [82]:
## 8) Crear una matriz 3 x 3 x 3 con valores randomicos
muestra = np.arange(27).reshape(3,3,3)
muestra

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [87]:
## 9) Crear una matriz 10 x 10 y encontrar el mayor y el menor

muestra = np.arange(100).reshape(10,10)
muestra.min()

0

In [88]:
muestra.max()

99

In [209]:
## 10) Sacar los colores RGB unicos en una imagen 
##(cuales rgb existen ej: 0, 0, 0 - 255,255,255 -> 2 colores)


import numpy as np
from scipy import ndimage
from scipy import misc
mapache = misc.face()
mapache

array([[[121, 112, 131],
        [138, 129, 148],
        [153, 144, 165],
        ...,
        [119, 126,  74],
        [131, 136,  82],
        [139, 144,  90]],

       [[ 89,  82, 100],
        [110, 103, 121],
        [130, 122, 143],
        ...,
        [118, 125,  71],
        [134, 141,  87],
        [146, 153,  99]],

       [[ 73,  66,  84],
        [ 94,  87, 105],
        [115, 108, 126],
        ...,
        [117, 126,  71],
        [133, 142,  87],
        [144, 153,  98]],

       ...,

       [[ 87, 106,  76],
        [ 94, 110,  81],
        [107, 124,  92],
        ...,
        [120, 158,  97],
        [119, 157,  96],
        [119, 158,  95]],

       [[ 85, 101,  72],
        [ 95, 111,  82],
        [112, 127,  96],
        ...,
        [121, 157,  96],
        [120, 156,  94],
        [120, 156,  94]],

       [[ 85, 101,  74],
        [ 97, 113,  84],
        [111, 126,  97],
        ...,
        [120, 156,  95],
        [119, 155,  93],
        [118, 154,  92]]

In [215]:
colores = np.unique(mapache.reshape(-1, mapache.shape[2]), axis=0)
colores

array([[  0,   0,   5],
       [  0,   0,   7],
       [  0,   0,   9],
       ...,
       [255, 248, 255],
       [255, 249, 255],
       [255, 252, 255]], dtype=uint8)

In [216]:
## 11) ¿Como crear una serie de una lista, diccionario 
##o arreglo?

import numpy as np
import pandas as pad
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))

serie_1 = pad.Series(mylist)
serie_2 = pad.Series(myarr)
serie_3 = pad.Series(mydict)

In [217]:
serie_1

0     a
1     b
2     c
3     e
4     d
5     f
6     g
7     h
8     i
9     j
10    k
11    l
12    m
13    n
14    o
15    p
16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
dtype: object

In [218]:
print(serie_2)

0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
11    11
12    12
13    13
14    14
15    15
16    16
17    17
18    18
19    19
20    20
21    21
22    22
23    23
24    24
25    25
dtype: int32


In [219]:
print(serie_3)

a     0
b     1
c     2
e     3
d     4
f     5
g     6
h     7
i     8
j     9
k    10
l    11
m    12
n    13
o    14
p    15
q    16
r    17
s    18
t    19
u    20
v    21
w    22
x    23
y    24
z    25
dtype: int64


In [150]:
## 12) ¿Como convertir el indice de una serie en una columna de un DataFrame?

mylist2 = list('abcedfghijklmnopqrstuvwxyz')
myarr2 = np.arange(26)
mydict2 = dict(zip(mylist2, myarr2))
ser = pd.Series(mydict2) 

# Transformar la serie en dataframe y hacer una columna indice
aqui = pd.DataFrame(ser).reset_index().set_index(myarr)
print(aqui)

   index   0
0      a   0
1      b   1
2      c   2
3      e   3
4      d   4
5      f   5
6      g   6
7      h   7
8      i   8
9      j   9
10     k  10
11     l  11
12     m  12
13     n  13
14     o  14
15     p  15
16     q  16
17     r  17
18     s  18
19     t  19
20     u  20
21     v  21
22     w  22
23     x  23
24     y  24
25     z  25


In [224]:
## 13) ¿Como combinar varias series para hacer 
##un DataFrame?

import pandas as pd
import numpy as np
ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))

In [225]:

datos = pd.DataFrame(ser1)
datos[1] = ser2
datos

0   1
0   a   0
1   b   1
2   c   2
3   e   3
4   d   4
5   f   5
6   g   6
7   h   7
8   i   8
9   j   9
10  k  10
11  l  11
12  m  12
13  n  13
14  o  14
15  p  15
16  q  16
17  r  17
18  s  18
19  t  19
20  u  20
21  v  21
22  w  22
23  x  23
24  y  24
25  z  25

In [226]:

datos2 = pd.DataFrame(dict(serie1=ser1, serie2=ser2))
datos2

serie1  serie2
0       a       0
1       b       1
2       c       2
3       e       3
4       d       4
5       f       5
6       g       6
7       h       7
8       i       8
9       j       9
10      k      10
11      l      11
12      m      12
13      n      13
14      o      14
15      p      15
16      q      16
17      r      17
18      s      18
19      t      19
20      u      20
21      v      21
22      w      22
23      x      23
24      y      24
25      z      25

In [159]:
## 14) ¿Como obtener los items que esten en una serie A y no en una serie B?

ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])
datos = set(ser1) - set(ser2)
print(datos)

{1, 2, 3}


In [160]:
#15 ¿Como obtener los items que no son comunes en una serie A y serie B?
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

datos=pd.concat([ser1,ser2]).drop_duplicates(keep=False)
print(datos)



0    1
1    2
2    3
2    6
3    7
4    8
dtype: int64


In [161]:
## 16) ¿Como obtener el numero de veces que se repite un valor en una serie?

ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))

print(ser.value_counts())


a    6
c    5
g    5
e    4
h    3
d    3
f    2
b    2
dtype: int64


In [177]:
## 17) Como mantener los 2 valores mas repetidos de una serie, y a los demas valores cambiarles por 0 ?

np.random.RandomState(100)
ser = pd.Series(np.random.randint(1, 5, [12]))
df = pd.DataFrame(ser,columns=["valor"])
cont = df["valor"].value_counts()
cont.sort_values()
values = cont.head(2).index
df[(df != values[0]) & (df != values[1])] = 0
df

valor
0       1
1       1
2       1
3       0
4       0
5       4
6       0
7       4
8       1
9       4
10      4
11      0

In [171]:
## 18) ¿Como transformar una serie de un arreglo de numpy a un DataFrame con un `shape` definido?

ser = pd.Series(np.random.randint(1, 10, 35))

serie = ser.values.reshape(7, 5)
df = pd.DataFrame(serie)
df


   0  1  2  3  4
0  9  8  4  9  3
1  2  5  3  4  1
2  5  5  6  6  9
3  5  9  3  1  7
4  9  5  4  3  5
5  6  8  7  1  6
6  7  2  4  1  6


0  1  2  3  4
0  9  8  4  9  3
1  2  5  3  4  1
2  5  5  6  6  9
3  5  9  3  1  7
4  9  5  4  3  5
5  6  8  7  1  6
6  7  2  4  1  6

In [179]:
## 19) ¿Obtener los valores de una serie conociendo la posicion por indice?

ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
pos = [0, 4, 8, 14, 20]
# a e i o u
ser[pos]

0     a
4     e
8     i
14    o
20    u
dtype: object

In [202]:
## 20) ¿Como anadir series vertical u horizontalmente a un DataFrame?
ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))
df = pd.DataFrame(ser1)

df[1] = ser1
df1


0  1
0  0  a
1  1  b
2  2  c
3  3  d
4  4  e

In [203]:
df = df.append(ser2,ignore_index=True)
df

0  1    2    3    4
0  0  0  NaN  NaN  NaN
1  1  1  NaN  NaN  NaN
2  2  2  NaN  NaN  NaN
3  3  3  NaN  NaN  NaN
4  4  4  NaN  NaN  NaN
5  a  b    c    d    e

In [227]:
## 21)¿Obtener la media de una serie agrupada por otra serie?

frutas = pd.Series(np.random.choice(['manzana', 'banana', 'zanahoria'], 10))
pesos = pd.Series(np.linspace(1, 10, 10))

datos = pd.DataFrame({"frutas": frutas, "pesos": pesos})
datos.groupby(['frutas']).mean()

pesos
frutas          
banana       4.5
manzana      8.0
zanahoria    5.0

In [ ]:
## 22) ¿Como importar solo columnas especificas de un archivo csv?

path = 'BostonHousing.csv'
cols = ['crim','zn','indus','chas','nox']
datos = pd.read_csv(path, nrows = 10, usecols=cols)
datos

pesos
frutas          
banana      4.80
manzana     5.25
zanahoria  10.00

In [187]:
## 22) ¿Como importar solo columnas especificas de un archivo csv?

##https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv.
path = 'BostonHousing.csv'
cols = ['crim','zn','indus','chas','nox']
datos = pd.read_csv(path, nrows = 10, usecols=cols)
datos

crim    zn  indus  chas    nox
0  0.00632  18.0   2.31     0  0.538
1  0.02731   0.0   7.07     0  0.469
2  0.02729   0.0   7.07     0  0.469
3  0.03237   0.0   2.18     0  0.458
4  0.06905   0.0   2.18     0  0.458
5  0.02985   0.0   2.18     0  0.458
6  0.08829  12.5   7.87     0  0.524
7  0.14455  12.5   7.87     0  0.524
8  0.21124  12.5   7.87     0  0.524
9  0.17004  12.5   7.87     0  0.524